
version: "3.3"
 
services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: miaoumiaou
      MYSQL_DATABASE: bdchatons
      MYSQL_USER: petitchat
      MYSQL_PASSWORD: miaou
    configs:
      - source: mysql_init
        target: /docker-entrypoint-initdb/mysql_init.sql
        mode:0555
    volumes: 
      - db-data:/var/lib/mysql
    networks:
      - backend   

  tomcat:
    environment:
      JDBC_URL: jdbc:mysql://db:3306/bdchatons?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: petitchat
      JDBC_PASS: miaou
    volumes:
      - $HOME/atomy/webapps:/usr/local/tomcat/webapps
    expose:
      - "8009"
    image: tomcat:latest
    depends_on:
      db
    networks:
      backend:
        aliases:
          - tomcats
      frontend:
        aliases:
          - tomcats
    deploy:
      mode: replicated
      replicas: 2
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3


  apache:
    ports:
      - "80"
    image: apache
    networks:
      frontend:
        aliases:
          - apaches
    configs:
      - source: apache_jk
        target: /etc/apache2/mods-available/jk.conf
        mode:044
      - source: apache_workers
        target: /etc/libapache2-mod-jk/workers.properties
        mode:0444
      - source: apache_virtualhosts
        target: /etc/apache2/sites-available/000-default.conf
        mode:0444
      - source: apache_conf
        target: /etc/apache2/apache2.conf
        mode:0444

networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay

configs:
  mysql_init:
    file: $HOME/atomy/mysql_init/mysql_init.sql
  apache_jk:
    file: $HOME/atomy/apache_conf/jk.conf
  apache_workers:
    file: $HOME/atomy/apache_conf/workers.properties
  apache_virtualhosts:
    file: $HOME/atomy/apache_conf/000-default.conf
  apache_conf:
    file: $HOME/atomy/apache_conf/apache2.conf

volumes:
  db-data:
